# Generated by Django 4.0.3 on 2023-10-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_sale_automobile_alter_sale_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='vin',
            field=models.CharField(max_length=50),
        ),
    ]
